events {
  worker_connections 1024;
}

http {
  upstream api       { server api:3000; }
  upstream web       { server web:4200; }
  upstream pwa       { server pwa:4200; }
  upstream admin     { server admin:4200; }

  # API
  server {
    listen 80;
    server_name api.localhost;
    location / {
      proxy_pass http://api;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }

  # Web operadores
  server {
    listen 80;
    server_name app.localhost;
    location / {
      proxy_pass http://web;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }

  # PWA mecánico
  server {
    listen 80;
    server_name pwa.localhost;
    location / {
      proxy_pass http://pwa;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }

  # Admin superadmin
  server {
    listen 80;
    server_name admin.localhost;
    location / {
      proxy_pass http://admin;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
